version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@5.1
  slack: circleci/slack@4.10.1
  node: circleci/node@4.5.2

parameters:
  alerts-slack-channel:
    type: string
    # Normally team specific alert channel e.g. hmpps_tech_alerts, syscon-alerts, dps_sed_alerts
    # This is to avoid a general alert dumping ground that no-one then monitors
    default: approved-premises-team-events
  releases-slack-channel:
    type: string
    # Normally dps-releases for most teams / projects
    default: approved-premises-team-events

  node-version:
    type: string
    default: 16.15-browsers

jobs:
  check_outdated:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: 'npm ci --no-audit'
      - run:
          name: Check version
          command: 'npm --version'
      - run:
          name: Run check
          command: 'npm outdated typescript govuk-frontend'
      - slack/notify:
          event: fail
          channel: << pipeline.parameters.alerts-slack-channel >>
          template: basic_fail_1

  e2e_environment_test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.32.1-focal
    circleci_ip_ranges: true # opt-in to jobs running on a restricted set of IPs
    steps:
      - run:
          name: Clone E2E repo
          command: |
            git clone https://github.com/ministryofjustice/hmpps-approved-premises-e2e.git .
      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - node/install-packages
      - run:
          name: E2E Check
          command: |
            npx playwright test
      - store_artifacts:
          path: test-results
          destination: test-results
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: 'dev'
          jira_update: true
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build_docker
      - e2e_environment_test:
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - deploy_dev
      - request-preprod-approval:
          type: approval
          requires:
            - deploy_dev
            - e2e_environment_test
      - hmpps/deploy_env:
          name: deploy_preprod
          env: 'preprod'
          context:
            - hmpps-common-vars
            - hmpps-approved-premises-ui-preprod
          requires:
            - request-preprod-approval
      - request-test-approval:
          type: approval
          requires:
            - deploy_dev
      - hmpps/deploy_env:
          name: deploy_test
          env: 'test'
          jira_update: true
          context:
            - hmpps-common-vars
            - hmpps-approved-premises-ui-stage
          filters:
            branches:
              only:
                - main
          requires:
            - helm_lint
            - build_docker
            - request-test-approval

  #      - request-prod-approval:
  #          type: approval
  #          requires:
  #            - deploy_preprod
  #      - hmpps/deploy_env:
  #          name: deploy_prod
  #          env: "prod"
  #          jira_update: true
  #          jira_env_type: production
  #          slack_notification: true
  #          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
  #          context:
  #            - hmpps-common-vars
  #            - approved-premises-ui-prod
  #          requires:
  #            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: '1 7 * * 1-5'
          filters:
            branches:
              only:
                - main
    jobs:
      - check_outdated:
          context:
            - hmpps-common-vars
      - hmpps/npm_security_audit:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: '20 7 * * 1'
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
