name: Generate Types

on:
  workflow_dispatch:

env:
  NODE_ENV: test
  API_CLIENT_ID: approved-premises
  API_CLIENT_SECRET: clientsecret

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: TODO
        run: echo "TODO - Generate types and open a PR"
